import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { parse } from './parse'
import { serialize } from './serialize'

// fullplannertext is gitignored real family data (see CLAUDE.md "Critical: data
// sensitivity") — present locally, restored from git history for parser development.
// This suite is the round-trip oracle described in docs-planning/PLAN.md.
const FIXTURE_PATH = resolve(__dirname, '../../fullplannertext')
const hasFixture = (() => {
  try {
    readFileSync(FIXTURE_PATH, 'utf8')
    return true
  } catch {
    return false
  }
})()

const describeIfFixture = hasFixture ? describe : describe.skip

describeIfFixture('round-trip against the real fullplannertext', () => {
  const src = readFileSync(FIXTURE_PATH, 'utf8')

  it('parses all 269 day records with no crash, plus the one real to-do-list block', () => {
    const { days, todoLists } = parse(src)
    expect(days).toHaveLength(269)
    expect(todoLists).toHaveLength(1)
  })

  // Banner.raw preserves exactly what she typed, including asterisk-count drift the
  // app exists to self-heal (CLAUDE.md: asterisk count is "derived at render/export
  // time, never stored"). serialize() regenerates it from position, so a banner whose
  // original count was already wrong (real case: Mar 9's sole banner is typed
  // "**Maryville spring break!!") legitimately changes shape on its first round trip.
  // Normalize that one documented dimension before the structural comparison; the
  // asterisk-only-fix line-diff test below covers the same ground at the text level.
  function stripBannerOrdinal(days: ReturnType<typeof parse>['days']) {
    return days.map((day) => ({
      ...day,
      banners: day.banners.map((b) => ({ ...b, raw: b.raw.replace(/^(\t?)\*+/, '$1') })),
    }))
  }

  it('parse(serialize(parse(src))) deep-equals parse(src), modulo documented asterisk-count fixes', () => {
    const { days, todoLists } = parse(src)
    const reparsed = parse(serialize(days, todoLists))
    expect(stripBannerOrdinal(reparsed.days)).toEqual(stripBannerOrdinal(days))
    expect(reparsed.todoLists).toEqual(todoLists)
  })

  it('is a fixed point after one correcting round trip (further round trips change nothing)', () => {
    const first = parse(src)
    const once = parse(serialize(first.days, first.todoLists))
    const twice = parse(serialize(once.days, once.todoLists))
    expect(twice).toEqual(once)
  })

  it('serialize(parse(src)) diffed against src contains only documented fixes', () => {
    const { days, todoLists } = parse(src)
    const out = serialize(days, todoLists)

    const srcLines = src.split('\n')
    const outLines = out.split('\n')

    // Compare non-blank, non-separator "content" lines in order — banners and entries.
    // Blank-line counts and separator-dot-counts are allowed to differ (documented
    // whitespace normalization); every other line must match verbatim, or differ only
    // by its leading asterisk run (documented ordinal-renumbering fix).
    // The file-level title ("⚫️ 2026 Masterplan Hx") has no home in the Day domain
    // model (it's not per-day data) and is intentionally not regenerated by serialize.
    const isNoise = (l: string) => l.trim() === '' || /^…+$/.test(l)
    const srcContent = srcLines.filter((l) => !isNoise(l)).filter((l) => !l.startsWith('⚫️'))
    const outContent = outLines.filter((l) => !isNoise(l))

    expect(outContent).toHaveLength(srcContent.length)

    const unexpectedDiffs: { index: number; src: string; out: string }[] = []
    for (let i = 0; i < srcContent.length; i++) {
      const a = srcContent[i]
      const b = outContent[i]
      if (a === b) continue

      const stripStars = (l: string) => l.replace(/^(\t?)\*+/, '$1')
      const isAsteriskOnlyFix = /^\t?\*+/.test(a) && /^\t?\*+/.test(b) && stripStars(a) === stripStars(b)
      const isTrailingWhitespaceFix = a.trimEnd() === b.trimEnd()

      if (!isAsteriskOnlyFix && !isTrailingWhitespaceFix) {
        unexpectedDiffs.push({ index: i, src: a, out: b })
      }
    }

    expect(unexpectedDiffs).toEqual([])
  })
})
